debug: false
uuid: 788336c1-2526-4059-bacf-f910fe7db24e
token_id: GvZq4atPd12ZlXzM
token: vIUfF3lUznJGNph4hOmE9Ibcq1sS6y1XOP8IaYpyINut0LOhrjKWgB7st588qaU5
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/192.168.1.20/fullchain.pem
    key: /etc/letsencrypt/live/192.168.1.20/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://192.168.1.20'
